homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 182
  unit_system: metric
  time_zone: Europe/Sofia
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 50
  icon: mdi:home

http:
  api_password: !secret api_password
  base_url: !secret base_url
  
config:
cloud:
sun:
frontend:
recorder:
  purge_interval: 1
  purge_keep_days: 1
  include:
    domains:
      - automation
      - binary_sensor
      - input_boolean
      - input_number
      - sensor
      - switch
mqtt:
  discovery: True
  discovery_prefix: ha


automation: !include_dir_merge_list automation/
group: !include_dir_merge_named group/
switch: !include_dir_merge_list switch/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
input_boolean: !include input/boolean.yaml
input_number: !include input/number.yaml
script: !include_dir_merge_named scripts/
notify: !include_dir_merge_list notify/

device_tracker:
  - platform: meraki
    secret: !secret meraki_secret
    validator: !secret meraki_validator
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret
  - platform: webostv
    host: '192.168.0.149'
    mac: 'c8:02:10:2f:b2:50'
    name: Living Room TV
    turn_on_action:
      service: broadlink.send_packet_192_168_0_141
      data:
        packet: 'JgDgAAABJ5URFBEUETgSExITEhMRFBEUETkROBITEjgRORE4EjgSOBEUERQRFBE4EhMSExEUERQROBI4EjgRFBE5ETgSOBI4EQAFKgABKEoSAAxcAAEoSxEADF0AASlKEQAMXQABJ0sRAAxdAAEoShIADFwAAShLEQAMXAABKUoRAAxdAAEpSRIADF0AASdLEgAMXQABKUkSAAxdAAEpSRIADF0AASlJEgAMXQABKEoSAAxcAAEpShEADF0AAShKEQAMXQABKEoSAAxcAAEoSxEADF0AASlKEQAMXQABKUoRAA0FAAAAAAAAAAA='
ifttt:
  key: !secret ifttt_key
customizer:
  custom_ui: local